[build]
  base = "web"
  publish = "web/public"
  command = "npm install && npm run build"
  ignore = "git diff --quiet HEAD^ HEAD -- ."

[build.environment]
  YARN_FLAGS = "--no-ignore-optional"
  API_URL = "https://api-dev.pathwar.land/"
  KEYCLOAK_REALM = "Pathwar-Dev"

[context.production.environment]
  API_URL = "https://api.pathwar.land/"
  KEYCLOAK_REALM = "Pathwar"
