version: '3.7'

services:
  pathwar-dev:
    image: pathwar/pathwar:latest
    restart: on-failure
    entrypoint:
      - ./wait-for-it.sh
      - db:3306
      - "--"
    environment:
      # specific to prod
      - VIRTUAL_HOST=${API_DEV_VIRTUAL_HOST}
      - VIRTUAL_PORT=8000
      # loaded from .env
      - API_URN
      - SENTRY_DSN
    command:
      - pathwar
      - --debug
      - --sentry-dsn=$SENTRY_DSN
      - api
      - --urn=$API_URN
      - server
      - --bind=0.0.0.0:8000
      # - --cors-allowed-origins=https://www.pathwar.land ## FIXME: enable in production
    depends_on:
      - db
      - mailserver
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - service-proxy
      - internal

  pathwar-unsafe:
    image: pathwar/pathwar:latest
    restart: on-failure
    entrypoint:
      - ./wait-for-it.sh
      - db:3306
      - "--"
    environment:
      # specific to prod
      - VIRTUAL_HOST=${API_UNSAFE_VIRTUAL_HOST}
      - VIRTUAL_PORT=8000
      # loaded from .env
      - API_URN
      - SENTRY_DSN
    command:
      - pathwar
      - --debug
      - --sentry-dsn=$SENTRY_DSN
      - api
      - --urn=$API_URN
      - --sso-unsafe
      - server
      - --bind=0.0.0.0:8000
      # - --cors-allowed-origins=https://www.pathwar.land ## FIXME: enable in production
    depends_on:
      - db
      - mailserver
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - service-proxy
      - internal

  mailserver:
    image: fgribreau/smtp-to-sendgrid-gateway
    restart: on-failure
    ports:
      - 25:25
    environment:
      - SENDGRID_API
    networks:
      - internal

  db:
    image: mariadb:10
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=uns3cur3
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_DATABASE=pathwar
    networks:
      - internal
    command:
      - mysqld
      - --character-set-server=utf8mb4

  forestadmin:
    image: pathwar/forestadmin:latest
    environment:
      # specific to prod
      - VIRTUAL_HOST=${ADMIN_DEV_VIRTUAL_HOST}
      - VIRTUAL_PORT=3310
      - APPLICATION_HOST=${ADMIN_DEV_VIRTUAL_HOST}
      - APPLICATION_PORT=3310
      - DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@db:3306/pathwar
      - DATABASE_SSL=false
      # loaded from .env
      - FOREST_AUTH_SECRET
      - FOREST_ENV_SECRET
    networks:
      - service-proxy
      - internal

volumes:
  db_data:
    driver: local

networks:
  service-proxy:
    external: true
  internal:
